Repository PND-Gamjakkang/PND-Server, pull requests merged in 2024-09, with the labels that each got.

#168 ✨ [Deploy] test 코드 사용하지 않음
  build.gradle
Labels: :four_leaf_clover: 혜진, 🌐 Release

#170 ✨ [Feat] Report 생성 log 추가
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, ✨ Feat

#171 🚨 [Fix] Report index.ts 확인 위해 테스트 코드로 수정
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#172 ✏️ [Fix] Reort 생성을 위한 index.ts 파일 실행 위치 수정 (deploy, local 다름)
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/src/file-writer.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#173 ✏️ [Fix] Report - File 로드 위치 수정(업로드,삭제) - ReportServiceImpl
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#174 ✏️ [Fix] report log 추가
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
Labels: ✨ Feat, 🚨 Fix

#176 [Deploy] CI/CD 완료 - Docker, Github Action을 이용한 CI/CD 구현 완료
  .github/workflows/aws.yml
Labels: :four_leaf_clover: 혜진, ✨ Feat, 🌐 Release

#178 ✨ [Feat] Github Report - Commits by Hour 기능 추가(애니메이션 추가 필요)
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/src/aggregate-repo-info.ts
  src/main/resources/scripts/3d-contrib/src/create-3d-contrib.ts
  src/main/resources/scripts/3d-contrib/src/create-graph-commits.ts
  src/main/resources/scripts/3d-contrib/src/create-svg.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
  src/main/resources/scripts/3d-contrib/src/type.ts
Labels: :four_leaf_clover: 혜진, ✨ Feat

#180 ✨ [Feat] jar 파일이 PND-Server.jar로 생성되도록 수정
  build.gradle
  src/main/resources/scripts/3d-contrib/src/create-svg.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
  src/main/resources/scripts/3d-contrib/src/type.ts
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#186 ✨ [Feat] github report 회고록 가이드 추가
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/src/create-graph-commits.ts
  src/main/resources/scripts/3d-contrib/src/create-retrospect-guide.ts
  src/main/resources/scripts/3d-contrib/src/create-svg.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
  src/main/resources/scripts/3d-contrib/src/type.ts
Labels: :four_leaf_clover: 혜진, ✨ Feat, 🚨 Fix

#187 ✏️ [Fix] report - 더미데이터 -> 통신 후 받는 데이터
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#188 🎨 리드미 자동생성 API 프롬프트 수정
  src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java
Labels: :rainbow: 지운, 🚨 Fix

#189 🩹 리드미 자동생성 API 프롬프트 수정
  src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java
Labels: :rainbow: 지운, 🚨 Fix

#190 📝 다이어그램 프롬프트 영어로 변경
  src/main/java/com/server/pnd/diagram/service/DiagramService.java
Labels: :rainbow: 지운, 🚨 Fix

#191 📝 프롬프트 한국어로 변경, 추가
  src/main/java/com/server/pnd/diagram/service/DiagramService.java
Labels: :rainbow: 지운, 🚨 Fix
