Repository PND-Gamjakkang/PND-Server, pull requests merged in 2024-08, with the labels that each got.

#51 🚨 [Fix] 프로젝트 생성 - fix response dto
  src/main/java/com/server/pnd/classDiagram/service/ChatGPTService.java
  src/main/java/com/server/pnd/classDiagram/service/DiagramServiceImpl.java
  src/main/java/com/server/pnd/project/dto/ProjectCreatedResponseDto.java
  src/main/java/com/server/pnd/project/service/ProjectServiceImpl.java
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#53 🧪 [Test] 클래스다이어그램 생성 테스트 API
  src/main/java/com/server/pnd/classDiagram/service/ChatGPTService.java
  src/main/java/com/server/pnd/classDiagram/service/DiagramServiceImpl.java
  src/main/java/com/server/pnd/domain/ClassDiagram.java
  src/main/java/com/server/pnd/test/controller/TestController.java
  src/main/java/com/server/pnd/test/dto/ClassDiagramCreatedRequestDto.java
  src/main/java/com/server/pnd/test/service/TestService.java
  src/main/java/com/server/pnd/test/service/TestServiceImpl.java
Labels: :four_leaf_clover: 혜진, :test_tube: Test

#56 🔧 ChatGPTConfig 파일 추가
  src/main/java/com/server/pnd/util/config/ChatGPTConfig.java
Labels: :rainbow: 지운, :wrench: Settings

#59 🎨 ChatRequestMsgDto 추가 및 config 파일 구조 재배치
  src/main/java/com/server/pnd/classDiagram/gpt/config/ApplicationConfig.java
  src/main/java/com/server/pnd/classDiagram/gpt/config/ChatGPTConfig.java
  src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatCompletionDto.java
  src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatRequestMsgDto.java
Labels: :rainbow: 지운, 🛠️ Refactoring, ✨ Feat

#60 🎨 ChatCompletionDto 추가
  src/main/java/com/server/pnd/classDiagram/gpt/dto/ChatCompletionDto.java
Labels: :rainbow: 지운, 🛠️ Refactoring, ✨ Feat

#61 ✨ ChatGPT API 사용 로직 구현 완료
  src/main/java/com/server/pnd/classDiagram/controller/DiagramController.java
  src/main/java/com/server/pnd/classDiagram/dto/DiagramRequestDto.java
  src/main/java/com/server/pnd/classDiagram/gpt/config/ChatGPTConfig.java
  src/main/java/com/server/pnd/classDiagram/service/ChatGPTService.java
  src/main/java/com/server/pnd/classDiagram/service/ClassDiagramService.java
  src/main/java/com/server/pnd/classDiagram/service/DiagramService.java
  src/main/java/com/server/pnd/classDiagram/service/DiagramServiceImpl.java
  src/main/java/com/server/pnd/classDiagram/service/QuestionService.java
Labels: :rainbow: 지운, ✨ Feat

#65 🌐 ChatGPT API 통신 연결 완료
  src/main/java/com/server/pnd/classDiagram/service/ClassDiagramService.java
  src/main/java/com/server/pnd/classDiagram/service/QuestionService.java
  src/main/java/com/server/pnd/gpt/config/ApplicationConfig.java
  src/main/java/com/server/pnd/gpt/config/ChatGPTConfig.java
  src/main/java/com/server/pnd/gpt/dto/ChatCompletionDto.java
  src/main/java/com/server/pnd/gpt/dto/ChatRequestMsgDto.java
  src/main/resources/application.properties
Labels: :rainbow: 지운, ✨ Feat, 🚨 Fix

#66 📝 Sequence Diagram 엔티티 추가
  src/main/java/com/server/pnd/domain/SequenceDiagram.java
Labels: :rainbow: 지운, :wrench: Settings

#76 🚨 [Fix] Repo, Readme 수정 관련 오 수정
  src/main/java/com/server/pnd/domain/Repo.java
  src/main/java/com/server/pnd/readme/controller/ReadmeController.java
  src/main/java/com/server/pnd/readme/repository/ReadmeRepository.java
  src/main/java/com/server/pnd/readme/service/ReadmeService.java
  src/main/java/com/server/pnd/readme/service/ReadmeServiceImpl.java
  src/main/java/com/server/pnd/repo/service/RepoServiceImpl.java
  src/main/java/com/server/pnd/test/dto/ClassDiagramCreatedRequestDto.java
  src/main/java/com/server/pnd/test/service/TestServiceImpl.java
  src/main/resources/application.properties
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#81 🚨 시퀀스 다이어그램 GPT 생성 오류 해결
  src/main/java/com/server/pnd/diagram/service/DiagramService.java
Labels: :rainbow: 지운, 🚨 Fix

#83 ✨[Feat] Github report API 구현 1 - 깃허브 api로 event 가져오기 & 이미지 생성 연습
  src/main/java/com/server/pnd/report/controller/ReportController.java
  src/main/java/com/server/pnd/report/dto/EventInfoDto.java
  src/main/java/com/server/pnd/report/dto/GitHubEvent.java
  src/main/java/com/server/pnd/report/service/ReportService.java
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
Labels: :four_leaf_clover: 혜진, ✨ Feat

#85 ✨ [Feat] 깃허브 레포트 생성 - 필요한 파일 추가 & 깃허브 refresh token 로직 추가
  src/main/java/com/server/pnd/PndApplication.java
  src/main/java/com/server/pnd/domain/User.java
  src/main/java/com/server/pnd/oauth/service/GithubSocialLoginServiceImpl.java
  src/main/java/com/server/pnd/oauth/service/SocialLoginService.java
  src/main/java/com/server/pnd/report/service/ReportServiceImpl.java
  src/main/resources/scripts/3d-contrib/package.json
  src/main/resources/scripts/3d-contrib/sample-settings/ever-green.json
  src/main/resources/scripts/3d-contrib/sample-settings/gitblock.json
  src/main/resources/scripts/3d-contrib/sample-settings/multiple.json
  src/main/resources/scripts/3d-contrib/sample-settings/parts.json
  src/main/resources/scripts/3d-contrib/sample-settings/rainbow.json
  src/main/resources/scripts/3d-contrib/sample-settings/season.json
  src/main/resources/scripts/3d-contrib/sample-settings/spanish.json
  src/main/resources/scripts/3d-contrib/src/aggregate-user-info.ts
  src/main/resources/scripts/3d-contrib/src/color-template.ts
  src/main/resources/scripts/3d-contrib/src/create-3d-contrib.ts
  src/main/resources/scripts/3d-contrib/src/create-pie-language.ts
  src/main/resources/scripts/3d-contrib/src/create-radar-contrib.ts
  src/main/resources/scripts/3d-contrib/src/create-svg.ts
  src/main/resources/scripts/3d-contrib/src/file-writer.ts
  src/main/resources/scripts/3d-contrib/src/github-graphql.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
  src/main/resources/scripts/3d-contrib/src/settings-reader.ts
  src/main/resources/scripts/3d-contrib/src/type.ts
  src/main/resources/scripts/3d-contrib/src/utils.ts
Labels: :four_leaf_clover: 혜진, ✨ Feat

#91 🚨 [Fix] event 관련 오류 수정
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, 🚨 Fix

#93 ✨ [Feat] 깃허브 레포트 - 3D contrib 생성 구현 (깃허브 토큰 관련 수정 완료)
  src/main/resources/scripts/3d-contrib/src/aggregate-user-info.ts
  src/main/resources/scripts/3d-contrib/src/file-writer.ts
  src/main/resources/scripts/3d-contrib/src/index.ts
Labels: :four_leaf_clover: 혜진, ✨ Feat
